rootProject.name = "supervisor"
include( "redis-repository")
include("repository")
include("adapters")
include("core")
include("configuration")
include("yaml-configuration")
include("redis-repository")
include("util")
include("menu")
